client_config_backend: settings
client_config:
  client_id: 835124988936-dn2kuh7722eb3pqtj8bv51keg32dhs15.apps.googleusercontent.com
  client_secret: G8oLWgxB1Z6eK-XUmKCQBNpT

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive